name: 'Build with MCUXpresso'
description: 'Build a project with headless run of NXP MCUXpresso'
inputs:
  projects:
    description: 'the sub folder containing the MCU Project to build'
    required: true
  configs:
    description: 'the config name to be build for each project'
    required: true
  resultpath:
    description: 'the file which should be used as output after build'
    required: true
outputs:
  axf:
    description: The build binary file
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.projects }}
    - ${{ inputs.configs }}
    - ${{ inputs.resultpath }}
    
    
