name: 'Build with MCUXpresso'
description: 'Build a project with headless run of NXP MCUXpresso'
inputs:
  project:
    description: 'the sub folder containing the MCU Project to build'
    required: true
outputs:
  afx:
    description: The build binary file
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    
